In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
np.__version__

'1.24.3'

In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
print(arr)

[1 2 3 4 5]


In [9]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [10]:
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [11]:
print(arr.ndim)

3


In [12]:
x = np.array([1,3,5,7])

In [13]:
print(x[0])

1


In [14]:
print(x[2])

5


In [15]:
print(x[1]+(x[2]))

8


In [16]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [17]:
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [18]:
print(arr[1, 3])

9


In [19]:
print(arr[1, 2])

8


In [20]:
print(arr[1, -3])

8


In [21]:
print(arr[1, -2])

9


In [22]:
x = np.array([1,2,3,4,5,6,7])
print(x[1:5])

[2 3 4 5]


In [23]:
print(x[4:])

[5 6 7]


In [24]:
print(x[-3:-1])

[5 6]


In [25]:
print(x[4:7])

[5 6 7]


In [26]:
print(x[1:5:2])

[2 4]


In [27]:
print(x[::2])

[1 3 5 7]


In [28]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [29]:
print(arr[0:2, 2])

[3 8]


In [30]:
print(arr[0:1, 2])

[3]


In [31]:
print(arr[0:2, 1])

[2 7]


In [32]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [33]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
arr = arr.reshape(5,2)

In [35]:
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [36]:
arr = np.array([[1, 2, 3, 4, 5,11], [6, 7, 8, 9, 10,12]])
arr = arr.reshape(4,3)
arr

array([[ 1,  2,  3],
       [ 4,  5, 11],
       [ 6,  7,  8],
       [ 9, 10, 12]])

In [37]:
y = np.empty((3,2),dtype=int)
y

array([[0, 0],
       [0, 0],
       [0, 0]])

In [38]:
arr

array([[ 1,  2,  3],
       [ 4,  5, 11],
       [ 6,  7,  8],
       [ 9, 10, 12]])

In [39]:
type(arr)

numpy.ndarray

In [40]:
arr.shape

(4, 3)

In [41]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5, 11],
       [ 6,  7],
       [ 8,  9],
       [10, 12]])

In [42]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5, 11],
       [ 6,  7,  8,  9, 10, 12]])

In [43]:
arr.ndim

2

In [44]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5, 11],
       [ 6,  7,  8],
       [ 9, 10, 12]])

In [45]:
arr.ndim

2

In [46]:
arr.dtype

dtype('int64')

In [56]:
z = np.zeros((3,2,3),dtype=int)
z

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [48]:
arr.size

12

In [51]:
z.size

18

In [52]:
z.nbytes

144

In [53]:
arr.nbytes

96

In [57]:
aa = np.ones((3,2,3),dtype=int)
aa

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [63]:
z = np.full((3,2,3),9)
z

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [70]:
idn = np.identity((4), dtype = int)
idn

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [71]:
aa.ndim

3

In [72]:
import pandas as pd

In [73]:
pd.__version__

'1.5.3'

In [ ]:
df = pd.read_csv('data.csv')